version: 2
registries:
  interlok:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: ${{secrets.NEXUS_REPO_USER}}
    password: ${{secrets.NEXUS_REPO_PASSWORD}}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    registries:
      - "interlok"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"